#!/usr/bin/python
import re
aaa_config_regex_pattern = re.compile(r"^aaa +")
bonjour_config_regex_pattern = re.compile(r"^bonjour +")
cdp_config_regex_pattern = re.compile(r"^cdp +")
clock_config_regex_pattern = re.compile(r"^clock +")
crypto_config_regex_pattern = re.compile(r"^crypto +")
default_gateway_config_regex_pattern = re.compile(r"^ip default-gateway +")
dhcp_config_regex_pattern = re.compile(r"(^ip dhcp +|^ip helper +)")
dns_config_regex_pattern = re.compile(r"(^ip domain +|^ip name-server)")
dot1x_config_regex_pattern = re.compile(r"^dot1x +")
hostname_regex_pattern = re.compile(r"^hostname +")
interface_regex_pattern = re.compile(r"^interface +")
lldp_config_regex_pattern = re.compile(r"^lldp +")
logging_config_regex_pattern = re.compile(r"^logging +")
passwords_config_regex_pattern = re.compile(r"^passwords +")
radius_config_regex_pattern = re.compile(r"(^radius-server +|encrypted radius-server +)")
snmp_config_regex_pattern = re.compile(r"^snmp-server +")
sntp_config_regex_pattern = re.compile(r"(^sntp +|^encrypted sntp +)")
ssh_client_config_regex_pattern = re.compile(r"^ip ssh-client +")
ssh_config_regex_pattern = re.compile(r"(^ip ssh +|^encrypted ip ssh-client +)")
system_mode_regex_pattern =re.compile(r"^set system mode ")
tacacs_config_regex_pattern = re.compile(r"^tacacs-server +")
telnet_config_regex_pattern = re.compile(r"^ip telnet server +")
username_regex_pattern = re.compile(r"^username +")
web_server_config_regex_pattern = re.compile(r"(^ip http +| ip https +)")
ssd_config_regex_pattern = re.compile(r"(^ssd +|^no ssd +|^ssd-control-*|file SSD +)")
voice_vlan_config_regex_pattern = re.compile(r"^voice vlan +")
eee_config_regex_pattern = re.compile(r"^eee +")
green_ethernet_config_regex_pattern = re.compile(r"^green-ethernet +")
##START NOT DONE
arp_config_regex_pattern = re.compile(r"(^ip arp +|^arp +)")
bridge_config_regex_pattern = re.compile(r"^bridge +")
enable_config_regex_pattern = re.compile(r"^enable +")
gvrp_config_regex_pattern = re.compile(r"^gvrp +")
igmp_config_regex_pattern = re.compile(r"^ip igmp +")
ipv6_config_regex_pattern = re.compile(r"^ipv6 +")
jumbo_frame_config_regex_pattern = re.compile(r"^port jumbo-frame")
lacp_config_regex_pattern = re.compile(r"^lacp +")
port_channel_config_regex_pattern = re.compile(r"(^port-channel +|^Port-Channel +)")
qos_config_regex_pattern = re.compile(r"(^qos +|^class-map +|^policy-map +)")
rmon_config_regex_pattern = re.compile(r"^rmon +")
route_config_regex_pattern = re.compile(r"^ip route +")
security_suite_config_regex_pattern = re.compile(r"^security-suite +")
service_config_regex_pattern = re.compile(r"^service +")
source_guard_config_regex_pattern = re.compile(r"^ip source-guard +")
spanning_tree_config_regex_pattern = re.compile(r"^spanning-tree +")
system_router_config_regex_pattern = re.compile(r"^system router +")
tunnel_config_regex_pattern = re.compile(r"(^tunnel +|^Tunnel +)")
udld_config_regex_pattern = re.compile(r"^udld +")
#END
## multiline regex 
banner_config_regex_pattern = re.compile(r"(?s)^banner(.*?)(?:(?:\r*\n){2}|^\^C)", re.MULTILINE)
console_line_config_regex_pattern = re.compile(r"(?s)^line console(.*?)(?:(?:\r*\n){2}|^exit)", re.MULTILINE)
interface_config_regex_pattern = re.compile(r"(?s)^interface(.*?)(?:(?:\r*\n){2}|\!)", re.MULTILINE)
keys_regex_pattern = re.compile(r"(?s)^user-key(.*?)(?:(?:\r*\n){2}|exit)", re.MULTILINE)
ssh_line_config_regex_pattern = re.compile(r"(?s)^line ssh(.*?)(?:(?:\r*\n){2}|^exit)", re.MULTILINE)
vlan_config_regex_pattern = re.compile(r"(?s)^vlan database(.*?)(?:(?:\r*\n){2}|^exit)", re.MULTILINE)
